version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paywatcher
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
